name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  run-e2e-test:
    name: Run e2e testing
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run e2e test
      run: npm run test:e2e
    - name: Upload Playwright Report to github
      uses: actions/upload-artifact@v4
      with:
        name: e2e playwright-report
        path: ./playwright-report/

  run-api-test:
    name: Run api testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run api test
        run: npm run test:api
      - name: Upload Playwright Report to github
      uses: actions/upload-artifact@v4
      with:
        name: api playwright-report
        path: ./playwright-report/
